apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: wordpress-persistent-storage
  labels:
    app: wordpress
    tier: frontend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.105
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: mysql-persistent-storage
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.105
